var xml = new ActiveXObject('MSXML.DOMDocument');
xml.appendChild(xml.createProcessingInstruction("xml", "version=\"1.0\" encoding=\"UTF-8\""));

var aircraftCarrier = xml.createElement('aircraft-carrier');
xml.appendChild(aircraftCarrier);
	var name = xml.createElement('name');
	aircraftCarrier.appendChild(name);
	var personel = xml.createElement('personel');
	aircraftCarrier.appendChild(personel);
		var soldier = xml.createElement('soldier');
		personel.appendChild(soldier);
			var firstName = xml.createElement('first-name');
			soldier.appendChild(firstName);
			var lastName = xml.createElement('last-name');
			soldier.appendChild(lastName);
			var gender = xml.createElement('gender');
			soldier.appendChild(gender);
			var position = xml.createElement('position');
			soldier.appendChild(position);
			var age = xml.createElement('age');
			soldier.appendChild(age);
			var religion = xml.createElement('religion');
			soldier.appendChild(religion);
	var aircrafts = xml.createElement('aircraft');
	aircraftCarrier.appendChild(aircrafts);
		var aircraft = xml.createElement('aircraft');
		aircrafts.appendChild(aircraft);
			var model = xml.createElement('model');
			aircraft.appendChild(model);
			var cost = xml.createElement('cost');
			aircraft.appendChild(cost);
			var specifications = xml.createElement('specifications');
			aircraft.appendChild(specifications);
			var crew = xml.createElement('crew');
			specifications.appendChild(crew);
			var range = xml.createElement('range');
			specifications.appendChild(range);
			var weight = xml.createElement('weight');
			specifications.appendChild(weight);
	var battles = xml.createElement('battles');
	aircraftCarrier.appendChild(battles);
		var battle = xml.createElement('battle');
		battles.appendChild(battle);
			var battleName = xml.createElement('battle-name');
			battle.appendChild(battleName);
			var countries = xml.createElement('countries');
			battle.appendChild(countries);
			var country = xml.createElement('country');
			countries.appendChild(country);
			var countryName = xml.createElement('country-name');
			country.appendChild(countryName);
			var population = xml.createElement('population');
			country.appendChild(population);
			var duration = xml.createElement('duration');
			battle.appendChild(duration);
			var description = xml.createElement('description');
			battle.appendChild(description);
			var unitsLost = xml.createElement('units-lost');
			battle.appendChild(unitsLost);
	var manufacturers = xml.createElement('manufacturers');
	aircraftCarrier.appendChild(manufacturers);
		var manufacturer = xml.createElement('manufacturer');
		manufacturers.appendChild(manufacturer);
			var manufacturerName = xml.createElement('manufacturer-name');
			manufacturer.appendChild(manufacturerName);
			var established = xml.createElement('establised');
			manufacturer.appendChild(established);
			var staffCount = xml.createElement('staff-count');
			manufacturer.appendChild(staffCount);
			var revenue = xml.createElement('revenue');
			manufacturer.appendChild(revenue);
	
name.appendChild(xml.createTextNode("УСС Ентърпрайз"));
firstName.appendChild(xml.createTextNode("Честър"));
lastName.appendChild(xml.createTextNode("Нимиц"));
gender.appendChild(xml.createTextNode("мъж"));
position.appendChild(xml.createTextNode("адмирал"));
age.appendChild(xml.createTextNode("57"));
religion.appendChild(xml.createTextNode("християнин"));
model.appendChild(xml.createTextNode("BTD Destroyer"));
cost.appendChild(xml.createTextNode("$200000"));
crew.appendChild(xml.createTextNode("1"));
range.appendChild(xml.createTextNode("1098 км"));
weight.appendChild(xml.createTextNode("5244 кг"));
battleName.appendChild(xml.createTextNode("Битка при Мидуей"));
countryName.appendChild(xml.createTextNode("Съединени американски щати"));
population.appendChild(xml.createTextNode("313 милиона"));
duration.appendChild(xml.createTextNode("три дни"));
description.appendChild(xml.createTextNode("Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация."));
unitsLost.appendChild(xml.createTextNode("Сериозни загуби за японската армия"));
manufacturerName.appendChild(xml.createTextNode("Дъглас"));	
established.appendChild(xml.createTextNode("1921"));	
staffCount.appendChild(xml.createTextNode("25500"));	
revenue.appendChild(xml.createTextNode("$900 милиона"));

xml.save("JS_Generated.xml");